# -*- coding: utf-8 -*-
"""55.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1q6BvUpN3HkgnGiO1okNX9HBXnW_xArwH
"""

import matplotlib.pyplot as plt
import numpy as np

def value_of_fx(x):
    return x**3-x-1

def value_of_fxx(x):
    return 3*x**2-1



print("     Xi        |     f(xi)       |     f'(xi)         |        xi+1       | Approximation Error   | Relative Approximation Error")
print(" ")

x=50
i=0
iter_nmbr=[]
approximation_err=[]
while abs(value_of_fx(x))>= 10 ** -5:

    xi=x-(value_of_fx(x)/value_of_fxx(x))
    apprxmtn=abs(xi-x)
    rel_apprxmtn=(apprxmtn*100)/xi
    print(f"  {xi:10.6f}   {value_of_fx(x):15.6f}  {value_of_fxx(x):15.6f}     {xi:15.6f}    {apprxmtn:19.6f}    {rel_apprxmtn:20.4f}%    ")
    x=xi
    i=i+1
    iter_nmbr.append(i)
    approximation_err.append(apprxmtn)



x = np.array(iter_nmbr)
y = np.array(approximation_err)

plt.bar(x,y)
plt.xlabel("Iteration Number")
plt.ylabel("Approximation error")
plt.show()