# -*- coding: utf-8 -*-
"""lab8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16IOyGGHy0y1usg9SFWRlh4yOTl6Clw76
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

def f(x):
    return x**2

a = 0
b = 4

delta_x_choices = []
pp=0
left_riemann_sum_values = []
right_riemann_sum_values = []
xx=0
midpoint_sum_values = []
trapezoidal_sum_values=[]
init=1e-4
delta_x_choices.append(init)
exact_integral = (1/3) * (4**3 - 0**3)
while init<1:
  init+=1e-4
  delta_x_choices.append(init)
  xx+=1
for dx in delta_x_choices:
    n = int((b - a) / dx)
    #delta_x = (b - a) / n

    left_sum = 0.0
    right_sum = 0.0
    midpoint_sum = 0.0
    trapezoidal_sum = 0.0

    for i in range(n):
        left_sum += f(a + i * dx) * dx
    left_riemann_sum_values.append(left_sum)

    for i in range(n):
        right_sum += f(a + (i + 1) * dx) * dx
    right_riemann_sum_values.append(right_sum)

    for i in range(n):
        midpoint_sum += f(a + (i + 0.5) * dx) * dx
    midpoint_sum_values.append(midpoint_sum)


    for i in range(n):
        trapezoidal_sum += (f(a + i * dx) + f(a + (i + 1) * dx)) * dx / 2
    trapezoidal_sum_values.append(trapezoidal_sum)

results_table = pd.DataFrame({
    'Delta x  |': delta_x_choices,
    'Left Hand Riemann Sum  |': left_riemann_sum_values,
    'Right Hand Riemann Sum  |': right_riemann_sum_values,
    'Midpoint Sum  |': midpoint_sum_values,
    'Exact Integral  |': exact_integral,
})

pd.set_option('display.max_rows', None)
pd.set_option('display.width', 1000)
pd.set_option('display.max_columns', 100)

print(results_table)

plt.plot(delta_x_choices, left_riemann_sum_values, label="Left Riemann Sum")
plt.plot(delta_x_choices, right_riemann_sum_values, label="Right Riemann Sum")
plt.plot(delta_x_choices, midpoint_sum_values, label="Midpoint Riemann Sum")
plt.plot(delta_x_choices, trapezoidal_sum_values, label="Trapezoid Sum")
plt.xlabel('Delta x')
plt.ylabel('Sum')
plt.axhline(exact_integral, color='r', linestyle='--', label="Exact Integral")
plt.title('Delta x vs. Riemann Sums')
plt.legend()
plt.show()